# Generated by Django 6.1 on 2026-09-02 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('cover_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('added', 'Added'), ('reading', 'Reading'), ('read', 'Read')], default='added', max_length=20)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'book'), name='unique_user_book'), models.CheckConstraint(condition=models.Q(models.Q(('rating__gte', 1), ('rating__lte', 5)), ('rating__isnull', True), _connector='OR'), name='rating_between_1_and_5'), models.CheckConstraint(condition=models.Q(('status__in', ['added', 'reading', 'read'])), name='status_restriction')],
            },
        ),
    ]
